//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Addressbook.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IContactBook_Interface")]
    public interface IContactBook_Interface {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactBook_Interface/PERFORM_ACTIONS", ReplyAction="http://tempuri.org/IContactBook_Interface/PERFORM_ACTIONSResponse")]
        string PERFORM_ACTIONS(string ACTION_REQUEST);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContactBook_Interface/PERFORM_ACTIONS", ReplyAction="http://tempuri.org/IContactBook_Interface/PERFORM_ACTIONSResponse")]
        System.Threading.Tasks.Task<string> PERFORM_ACTIONSAsync(string ACTION_REQUEST);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContactBook_InterfaceChannel : Addressbook.ServiceReference1.IContactBook_Interface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContactBook_InterfaceClient : System.ServiceModel.ClientBase<Addressbook.ServiceReference1.IContactBook_Interface>, Addressbook.ServiceReference1.IContactBook_Interface {
        
        public ContactBook_InterfaceClient() {
        }
        
        public ContactBook_InterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContactBook_InterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactBook_InterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContactBook_InterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PERFORM_ACTIONS(string ACTION_REQUEST) {
            return base.Channel.PERFORM_ACTIONS(ACTION_REQUEST);
        }
        
        public System.Threading.Tasks.Task<string> PERFORM_ACTIONSAsync(string ACTION_REQUEST) {
            return base.Channel.PERFORM_ACTIONSAsync(ACTION_REQUEST);
        }
    }
}
